#!/usr/bin/python2

from __future__ import print_function


import remote_sheet
import idea_date
import storage
import spreadsheet

import argparse
import datetime


def prepare_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('idea_string', nargs='?')
    parser.add_argument('--list', help='list ideas', action='store_true')
    parser.add_argument('--setup', help='set up spreadsheet', action='store_true')
    return parser


def parse_args(parser):
    args = parser.parse_args()
    return args


def print_ideas(idea_list):
    if not idea_list:
        print('No ideas exist in the sheet..')
    else:
        for i, (d, idea_string) in enumerate(idea_list):
            print('%i: %s, %s' % (i, idea_date.date_to_string(d),
                              idea_string))


def setup_spreadsheet():
    spreadsheet_object = spreadsheet.setup_spreadsheet()
    remote_sheet.init_sheet(spreadsheet_object)
    storage.write_spreadsheet(spreadsheet_object)


def get_idea_spreadsheet():
    spreadsheet_object = storage.read_spreadsheet()
    if not spreadsheet_object:
        setup_spreadsheet()
        spreadsheet_object = storage.read_spreadsheet()
    return spreadsheet_object


def main():
    """Shows basic usage of the Sheets API.

    Creates a Sheets API service object and prints the names and majors of
    students in a sample spreadsheet:
    https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit
    """
    """https://docs.google.com/spreadsheets/d/1yHpDejkJ-znUIRmvNA4Z64fJPpBo29Kl11Z3WRpD3rA/edit?usp=sharing"""
    parser = prepare_parser()
    args = parse_args(parser)
    if args.list:
        spreadsheet_object = get_idea_spreadsheet()
        idea_list = remote_sheet.read_ideas(spreadsheet_object)
        print_ideas(idea_list)
    elif args.setup:
        setup_spreadsheet()
    elif args.idea_string:
        spreadsheet_object = get_idea_spreadsheet()
        time_stamp = idea_date.date_to_string(datetime.datetime.today())
        idea_string = args.idea_string
        remote_sheet.write_idea(time_stamp, idea_string, spreadsheet_object)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
